name: WakaTime Coding Statistics

on:
  schedule:
    - cron: '30 21 * * *'
    
  workflow_dispatch:
  
  push:
    branches:
    - main

jobs:
  update-readme:
    name: Profile Readme Dev Stats
    runs-on: ubuntu-latest
    steps:
      #- uses: anmol098/waka-readme-stats@master
      - uses: nick22985/Dev-Stats@V0.0.4
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_MESSAGE: "Update readme"
          SHOW_SHORT_INFO: "False"
          COMMIT_BY_ME: "True"
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_UPDATED_DATE: "False"
          SHOW_TIMEZONE: "False"
          SHOW_LOC_CHART: "False"
          SHOW_PROJECTS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_COMMIT: "False"
          SHOW_DAYS_OF_WEEK: "False"
